### ISSUE TITLE
Ios platform ready

### ISSUE THREAD

**Issue by pdkpavankumar** [oracle/cordova-plugin-emm-app-config#1]
when i install the plugin the app is not triggering the device ready method or ionic platform ready

**Comment by MrTechGadget** [comment]
Same issue on Android for me using ionic.

I am going to dig into this, but I don’t have any experience with writing Cordova plugins, so that t might be slow going but I will post my results.

**Comment by MrTechGadget** [comment]
Ok @pdkpavankumar , I have been able to fix this for Android at least, will need to test it back on my Mac for iOS.

The fix is simple, just commenting out two lines in the www/emmappconfig.js file. Line 12 and 14
```
channel.createSticky('onCordovaInfoReady');
// Tell cordova channel to wait on the CordovaInfoReady event
channel.waitForInitialization('onCordovaInfoReady');
```
to:
```
//channel.createSticky('onCordovaInfoReady');
// Tell cordova channel to wait on the CordovaInfoReady event
//channel.waitForInitialization('onCordovaInfoReady');
```
after making the change, remove and add the platform again.

Let me know if this works for you too!

**Comment by MrTechGadget** [comment]
I have tested this out on iOS and it works too.
For those of you who are interested in AppConfig with Ionic, I have published a tweaked cordova plugin that works right off the bat as it looks like Oracle is not interested in maintaining this project.

I am willing to maintain this project, many thanks to Oracle for getting the meat of this work done. I am looking into how I can integrate it further with Ionic, but it is working now.
[https://github.com/audioeng/cordova-plugin-appconfig](https://github.com/audioeng/cordova-plugin-appconfig)

**Comment by brunoborges** [comment]
@audioeng we will keep an eye on this for sure, and we are certainly interested. But it is just a matter of roadmap analysis and prioritization. :-)

Thanks for contributing

**Comment by MrTechGadget** [comment]
Thanks @brunoborges, I assumed due to the inactivity and being closed to contributing that it was just released but not being maintained. 

I certainly understand prioritization!

**Comment by lpchanora** [comment]
@audioeng , thanks for posting a fix.  We will take a look and if the fix can be applied generally, we will incorporate it into the plugin.

**Comment by lpchanora** [comment]
A new version (1.0.1) with the correct fix is available.  Instead of commenting out the code that causes problem, the correct fix is to change the channel event name.

To update to the new version, the plugin must first be removed from the project:
cordova plugin remove cordova-plugin-emm-app-config

Then add it back in:
cordova plugin add cordova-plugin-emm-app-config
